config/routes.rb
Rails.application.routes.draw do
  root to: "edais#index"
  resources :edais
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '収入' },
    { id: 3, name: '支出' }
  ]

  include ActiveHash::Associations
  has_many :edais  
  end

app/models/description.rb
class Description < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '講師謝礼' },
    { id: 3, name: '税金' },
    { id: 4, name: '会場費' },
    { id: 5, name: '郵送代' },
    { id: 6, name: '封筒、ハガキ、短冊' },
    { id: 7, name: 'コピー用紙、インクカートリッジ' },
    { id: 8, name: '句集代' },
    { id: 9, name: '次年度繰越' },
    { id: 10, name: '事業補助費' },
    { id: 11, name: '会費' },
    { id: 12, name: '句集代' },
    { id: 13, name: '前年度繰越' }
  ]

  include ActiveHash::Associations
  has_many :edais
end

app/models/edai.rb
class Edai < ApplicationRecord
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :balance
  belongs_to :my_description
  validates :balance_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :entry_day, presence: true
  validates :genre_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :my_description_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0} 
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '講師謝礼' },
    { id: 3, name: '会場費' },
    { id: 4, name: '通信費' },
    { id: 5, name: '運営経費' },
    { id: 6, name: '次年度繰越' },
    { id: 7, name: '事業補助費' },
    { id: 8, name: '会費' },
    { id: 9, name: '句集代' },
    { id: 10, name: '前年度繰越' },
  ]

  include ActiveHash::Associations
  has_many :edais  
  end

app/models/my_description.rb
class MyDescription < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '講師謝礼' },
    { id: 3, name: '税金' },
    { id: 4, name: '会場費' },
    { id: 5, name: '郵送代' },
    { id: 6, name: '封筒、ハガキ、短冊' },
    { id: 7, name: 'コピー用紙、インクカートリッジ' },
    { id: 8, name: '句集代' },
    { id: 9, name: '次年度繰越' },
    { id: 10, name: '事業補助費' },
    { id: 11, name: '会費' },
    { id: 12, name: '句集代' },
    { id: 13, name: '前年度繰越' }
  ]

  include ActiveHash::Associations
  has_many :edais
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/edais_controller.rb
class EdaisController < ApplicationController
  before_action :set_edai, only: [:edit, :update, :destroy]
  def index
    @edais = Edai.order(entry_day: "ASC")
    @edai_sum_balance = Edai.group(:balance_id).sum(:price)
    @edai_sum = Edai.group(:genre_id).sum(:price)
    @edai_sum_description = Edai.group(:my_description_id).sum(:price)
  end
  
  def new
    @edai = Edai.new
  end

  def create
    @edai = Edai.new(edai_params)
    if @edai.save
      redirect_to root_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @edai.update(edai_params)
      redirect_to root_path(@edai)
    else
      render :edit
    end
  end
  def destroy
    @edai.destroy
      redirect_to root_path
  end
  private
  def edai_params
    params.require(:edai).permit(:balance_id, :entry_day, :genre_id, :my_description_id, :price)
  end
  def set_edai
    @edai = Edai.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/edais_helper.rb
module EdaisHelper
end

app/views/edais/edit.html.erb
<h3>収支を登録する</h3>
  <%= form_with model: @edai, local: true do |f|%>
    <%= render partial: 'shared/error_messages', locals: { resource: @edai} %>
    <div class="field">
      <%= f.label :entry_day, "日付" %><br />
      <%= f.text_area :entry_day, class: :form__text, id:"entry_day" %>
    </div>

    <div class="field">
      <%= f.label :balance_id, "収入/支出" %><br />
      <%= f.collection_select(:balance_id, Balance.all, :id, :name, {}, {class:"balance-select"}) %>
    </div>

    <div class="field">
      <%= f.label :genre_id, "項目" %><br />
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
    </div>
    <div class="field">
      <%= f.label :my_description_id, "摘要" %><br />
      <%= f.collection_select(:my_description_id, MyDescription.all, :id, :name, {}, {class:"description-select"}) %>
    </div>
    <div class="field">
      <%= f.label :note, "備考" %><br />
      <%= f.text_area :note, class: :form__text, id:"note" %>
    </div>
    <div class="field">
      <%= f.label :price, "金額" %><br />
      <%= f.text_area :price, class: :form__text, id:"price" %>
    </div>
    <div class="actions">
      <%= f.submit "保存する", class: :form__btn  %>
    </div>
  <% end %>

app/views/edais/index.html.erb
  <h1> 会計ソフト　永代のトップページ </h1>
  <%= link_to "新規収支の登録", new_edai_path, method: :get,class: :nav__btn %>
    <table border="1", class = "list1" >
      <tr>
        <th>収入/支出</th>
        <th>日付</th>
        <th>項目</th>
        <th>摘要</th>
        <th>備考</th>
        <th>金額</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
  <% @edais.each do |edai| %>
          <tr>
            <td><%= edai.balance.name %></td>
            <td><%= edai.entry_day %></td>
            <td><%= edai.genre.name %></td>
            <td><%= edai.my_description.name %></td>
            <td><%= edai.note %></td>
            <td><%= edai.price %></td>
            <td><%= link_to '編集', edit_edai_path(edai.id), method: :get %></td>
            <td><%= link_to '削除',"/edais/#{edai.id}", method: :delete%>
          </tr>
  <% end %>
</table>
<div class = "genre">収支の合計</div>
<table border="1", class = "item_balance_sum" >
  <% @edai_sum_balance.each do |key,value| %>
      <% case key %>
        <% when 2 then %>
          <% key_str = "収入" %>
        <% when 3 then %>
          <% key_str = "支出" %>
      <% end %>
      <tr>
        <td><%= key_str%>
        <td><%= value.round %></td>
      </tr>
  <% end %>
</table>

  <div class = "genre">項目の合計</div>
    <table border="1", class = "item_sum" >
      <% @edai_sum.each do |key,value| %>
        <% case key%>
          <% when 2 then %>
            <% key_str = "講師謝礼" %>
          <% when 3 then %>
            <% key_str = "会場費" %>
          <% when 4 then %>
            <% key_str = "通信費" %>
          <% when 5 then %>
            <% key_str = "運営経費" %>
          <% when 6 then %>
            <% key_str = "次年度繰越金" %>
          <% when 7 then %>
            <% key_str = "事業補助費" %>
          <% when 8 then %>
            <% key_str = "会費" %>
          <% when 9 then %>
            <% key_str = "句集代" %>
          <% when 10 then %>
            <% key_str = "前年度繰越金"%>
        <% end %>
        <tr>
          <td><%= key_str %></td>
          <td><%= value.round %></td>
        </tr>
      <% end %>
    </table>

<div class = "genre">摘要の合計</div>
<table border="1", class = "item_sum" >
  <% @edai_sum_description.each do |key,value| %>
    <% case key%>
      <% when 2 then %>
        <% key_str = "講師謝礼" %>
      <% when 3 then %>
        <% key_str = "税金"%>
      <% when 4 then %>
        <% key_str = "会場費"%>
      <% when 5 then %>
        <% key_str = "郵送代" %>
      <% when 6 then %>
        <% key_str = "封筒、ハガキ、短冊" %>
      <% when 7 then %>
        <% key_str = "コピー用紙、インクカートリッジ"%>
      <% when 8 then %>
        <% key_str = "句集代" %>
      <% when 9 then %>
        <% key_str = "次年度繰越"%>
      <% when 10 then %>
        <% key_str = "事業補助費" %>
      <% when 11 then %>
        <% key_str = "会費"%>
      <% when 12 then %>
        <% key_str = "句集代" %>
      <% when 13 then %>
        <% key_str = "前年度繰越" %>
      <% end %>
    <tr>
      <td><%= key_str %></td>
      <td><%= value.round %></td>
    </tr>
  <% end %>
</table>

app/views/edais/new.html.erb
<h3>収支を登録する</h3>
  <%= form_with model: @edai, local: true do |f|%>
    <%= render partial: 'shared/error_messages', locals: { resource: @edai} %>
    <div class="field">
      <%= f.label :entry_day, "日付" %><br />
      <%= f.text_area :entry_day, class: :form__text, id:"entry_day" %>
    </div>

    <div class="field">
      <%= f.label :balance_id, "収入/支出" %><br />
      <%= f.collection_select(:balance_id, Balance.all, :id, :name, {}, {class:"balance-select"}) %>
    </div>

    <div class="field">
      <%= f.label :genre_id, "項目" %><br />
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
    </div>
    <div class="field">
      <%= f.label :my_description_id, "摘要" %><br />
      <%= f.collection_select(:my_description_id, MyDescription.all, :id, :name, {}, {class:"description-select"}) %>
    </div>
    <div class="field">
      <%= f.label :note, "備考" %><br />
      <%= f.text_area :note, class: :form__text, id:"note" %>
    </div>
    <div class="field">
      <%= f.label :price, "金額" %><br />
      <%= f.text_area :price, class: :form__text, id:"price" %>
    </div>
    <div class="actions">
      <%= f.submit "保存する", class: :form__btn  %>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EDai237549</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>